name: Build

on:
  workflow_dispatch: ~
  push:
    branches:
      - main
      - dev
    paths:
      - src/**
  pull_request:
    branches:
      - main
      - dev
  schedule:
    - cron: '0 22 * * 1'  # 06:00 AM +08:00 every Monday

jobs:
  unittest:
    name: Run unittests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install pnpm and dependencies
        uses: pnpm/action-setup@v2
        with:
          run_install: true
      - name: Run unittests
        run: pnpm test

  build:
    name: Build and push image onto dockerhub and ghcr
    if: ${{ (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/main' }}
    needs:
      - unittest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
      - name: Install dependencies
        run: pnpm install --prod
      - name: Build project
        run: pnpm build
      - name: Build kelly image
        uses: wdzeng/image@v2
        with:
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-password: ${{ secrets.DOCKERHUB_TOKEN }}
          variant: kelly
          platforms: linux/amd64,linux/arm64
          build-args: |
            BASE_IMAGE=alpine-base
            VARIANT=kelly
          repo-description: Get Shopee coins everyday
          repo-license: MIT
      - name: Build regular image
        uses: wdzeng/image@v2
        with:
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-password: ${{ secrets.DOCKERHUB_TOKEN }}
          init: false
          platforms: linux/amd64,linux/arm64
          build-args: |
            BASE_IMAGE=alpine-font
            VARIANT=''
          repo-description: Get Shopee coins everyday
          repo-license: MIT

  tag:
    name: Add tags to repository
    if: ${{ github.event_name == 'push' }}
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: version
        uses: wdzeng/version@v1
        with:
          prefix: v
      - name: Add tags
        run: |
          git tag -f ${{ steps.version.outputs.version }} main && \
          git push -f origin ${{ steps.version.outputs.version }}
